# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(926, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/timeIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.btnRedmineTaskAdd = QtWidgets.QPushButton(self.centralwidget)
        self.btnRedmineTaskAdd.setObjectName("btnRedmineTaskAdd")
        self.horizontalLayout_2.addWidget(self.btnRedmineTaskAdd)
        self.btnRedmineTaskEdit = QtWidgets.QPushButton(self.centralwidget)
        self.btnRedmineTaskEdit.setObjectName("btnRedmineTaskEdit")
        self.horizontalLayout_2.addWidget(self.btnRedmineTaskEdit)
        self.btnRedmineTaskDelete = QtWidgets.QPushButton(self.centralwidget)
        self.btnRedmineTaskDelete.setObjectName("btnRedmineTaskDelete")
        self.horizontalLayout_2.addWidget(self.btnRedmineTaskDelete)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.redmineTasks = QtWidgets.QTableView(self.centralwidget)
        self.redmineTasks.setObjectName("redmineTasks")
        self.verticalLayout_2.addWidget(self.redmineTasks)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.btnEvoTaskAdd = QtWidgets.QPushButton(self.centralwidget)
        self.btnEvoTaskAdd.setObjectName("btnEvoTaskAdd")
        self.horizontalLayout_3.addWidget(self.btnEvoTaskAdd)
        self.btnEvoTaskEdit = QtWidgets.QPushButton(self.centralwidget)
        self.btnEvoTaskEdit.setObjectName("btnEvoTaskEdit")
        self.horizontalLayout_3.addWidget(self.btnEvoTaskEdit)
        self.btnEvoTaskDelete = QtWidgets.QPushButton(self.centralwidget)
        self.btnEvoTaskDelete.setObjectName("btnEvoTaskDelete")
        self.horizontalLayout_3.addWidget(self.btnEvoTaskDelete)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.evoTasks = QtWidgets.QTableView(self.centralwidget)
        self.evoTasks.setObjectName("evoTasks")
        self.verticalLayout_2.addWidget(self.evoTasks)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 31, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnEvoTaskGenerate = QtWidgets.QPushButton(self.centralwidget)
        self.btnEvoTaskGenerate.setMinimumSize(QtCore.QSize(0, 23))
        self.btnEvoTaskGenerate.setObjectName("btnEvoTaskGenerate")
        self.verticalLayout.addWidget(self.btnEvoTaskGenerate)
        self.btnSendToEvo = QtWidgets.QPushButton(self.centralwidget)
        self.btnSendToEvo.setMinimumSize(QtCore.QSize(0, 23))
        self.btnSendToEvo.setObjectName("btnSendToEvo")
        self.verticalLayout.addWidget(self.btnSendToEvo)
        self.btnSendToRedmine = QtWidgets.QPushButton(self.centralwidget)
        self.btnSendToRedmine.setMinimumSize(QtCore.QSize(0, 23))
        self.btnSendToRedmine.setObjectName("btnSendToRedmine")
        self.verticalLayout.addWidget(self.btnSendToRedmine, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 926, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu2 = QtWidgets.QMenu(self.menu)
        self.menu2.setObjectName("menu2")
        MainWindow.setMenuBar(self.menubar)
        self.actionHamster = QtWidgets.QAction(MainWindow)
        self.actionHamster.setObjectName("actionHamster")
        self.actionRedmine = QtWidgets.QAction(MainWindow)
        self.actionRedmine.setObjectName("actionRedmine")
        self.menuSettings = QtWidgets.QAction(MainWindow)
        self.menuSettings.setObjectName("menuSettings")
        self.setProjects = QtWidgets.QAction(MainWindow)
        self.setProjects.setObjectName("setProjects")
        self.importFromRedmine = QtWidgets.QAction(MainWindow)
        self.importFromRedmine.setObjectName("importFromRedmine")
        self.importFromHamster = QtWidgets.QAction(MainWindow)
        self.importFromHamster.setObjectName("importFromHamster")
        self.menu2.addAction(self.importFromRedmine)
        self.menu2.addAction(self.importFromHamster)
        self.menu.addAction(self.menuSettings)
        self.menu.addAction(self.menu2.menuAction())
        self.menu.addAction(self.setProjects)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "pyTime"))
        self.label.setText(_translate("MainWindow", "Redmine"))
        self.btnRedmineTaskAdd.setText(_translate("MainWindow", "Добавить"))
        self.btnRedmineTaskEdit.setText(_translate("MainWindow", "Редактировать"))
        self.btnRedmineTaskDelete.setText(_translate("MainWindow", "Удалить"))
        self.label_2.setText(_translate("MainWindow", "Evolution"))
        self.btnEvoTaskAdd.setText(_translate("MainWindow", "Добавить"))
        self.btnEvoTaskEdit.setText(_translate("MainWindow", "Изменить"))
        self.btnEvoTaskDelete.setText(_translate("MainWindow", "Удалить"))
        self.btnEvoTaskGenerate.setText(_translate("MainWindow", "Сгенерировать записи evo"))
        self.btnSendToEvo.setText(_translate("MainWindow", "Отправить в evo"))
        self.btnSendToRedmine.setText(_translate("MainWindow", "Отправить в redmine"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu2.setTitle(_translate("MainWindow", "Импорт часов"))
        self.actionHamster.setText(_translate("MainWindow", "Hamster"))
        self.actionRedmine.setText(_translate("MainWindow", "Redmine"))
        self.menuSettings.setText(_translate("MainWindow", "Настройки"))
        self.setProjects.setText(_translate("MainWindow", "Сопоставление проектов"))
        self.importFromRedmine.setText(_translate("MainWindow", "Redmine"))
        self.importFromHamster.setText(_translate("MainWindow", "Hamster"))

