# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'redmineEvoProjects.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RedminEevoProjects(object):
    def setupUi(self, RedminEevoProjects):
        RedminEevoProjects.setObjectName("RedminEevoProjects")
        RedminEevoProjects.resize(486, 389)
        self.gridLayout = QtWidgets.QGridLayout(RedminEevoProjects)
        self.gridLayout.setObjectName("gridLayout")
        self.tabs = QtWidgets.QTabWidget(RedminEevoProjects)
        self.tabs.setObjectName("tabs")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.tab1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.redmineProjectsView = QtWidgets.QListView(self.tab1)
        self.redmineProjectsView.setObjectName("redmineProjectsView")
        self.verticalLayout_2.addWidget(self.redmineProjectsView)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.tab1)
        self.label.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.evoProject = QtWidgets.QLineEdit(self.tab1)
        self.evoProject.setMinimumSize(QtCore.QSize(150, 0))
        self.evoProject.setObjectName("evoProject")
        self.verticalLayout_3.addWidget(self.evoProject)
        self.saveRedmineEvoProject = QtWidgets.QPushButton(self.tab1)
        self.saveRedmineEvoProject.setObjectName("saveRedmineEvoProject")
        self.verticalLayout_3.addWidget(self.saveRedmineEvoProject)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabs.addTab(self.tab1, "")
        self.hamstertab = QtWidgets.QWidget()
        self.hamstertab.setObjectName("hamstertab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.hamstertab)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.hamstertab)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.hamsterProjectView = QtWidgets.QListView(self.hamstertab)
        self.hamsterProjectView.setObjectName("hamsterProjectView")
        self.verticalLayout_4.addWidget(self.hamsterProjectView)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.hamstertab)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.redmineCombo = QtWidgets.QComboBox(self.hamstertab)
        self.redmineCombo.setMinimumSize(QtCore.QSize(200, 0))
        self.redmineCombo.setObjectName("redmineCombo")
        self.verticalLayout_5.addWidget(self.redmineCombo)
        self.saveHumsterProject = QtWidgets.QPushButton(self.hamstertab)
        self.saveHumsterProject.setObjectName("saveHumsterProject")
        self.verticalLayout_5.addWidget(self.saveHumsterProject)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.tabs.addTab(self.hamstertab, "")
        self.gridLayout.addWidget(self.tabs, 0, 0, 1, 1)

        self.retranslateUi(RedminEevoProjects)
        self.tabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(RedminEevoProjects)

    def retranslateUi(self, RedminEevoProjects):
        _translate = QtCore.QCoreApplication.translate
        RedminEevoProjects.setWindowTitle(_translate("RedminEevoProjects", "Dialog"))
        self.label_2.setText(_translate("RedminEevoProjects", "Проекты redmine"))
        self.label.setText(_translate("RedminEevoProjects", "Проект в evolution"))
        self.saveRedmineEvoProject.setText(_translate("RedminEevoProjects", "Сохранить"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab1), _translate("RedminEevoProjects", "Redmine to evo"))
        self.label_3.setText(_translate("RedminEevoProjects", "Категория в Humster"))
        self.label_4.setText(_translate("RedminEevoProjects", "Redmine"))
        self.saveHumsterProject.setText(_translate("RedminEevoProjects", "Сохранить"))
        self.tabs.setTabText(self.tabs.indexOf(self.hamstertab), _translate("RedminEevoProjects", "Hamster to redmine"))

