# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SettingsForm(object):
    def setupUi(self, SettingsForm):
        SettingsForm.setObjectName("SettingsForm")
        SettingsForm.resize(450, 307)
        self.gridLayout = QtWidgets.QGridLayout(SettingsForm)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(SettingsForm)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.listView = QtWidgets.QListView(SettingsForm)
        self.listView.setObjectName("listView")
        self.verticalLayout_5.addWidget(self.listView)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(SettingsForm)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(SettingsForm)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton = QtWidgets.QPushButton(SettingsForm)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_2 = QtWidgets.QLabel(SettingsForm)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(SettingsForm)
        self.lineEdit.setMinimumSize(QtCore.QSize(125, 0))
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_3 = QtWidgets.QLabel(SettingsForm)
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(SettingsForm)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_4 = QtWidgets.QLabel(SettingsForm)
        self.label_4.setObjectName("label_4")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(SettingsForm)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.pushButton_4 = QtWidgets.QPushButton(SettingsForm)
        self.pushButton_4.setObjectName("pushButton_4")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pushButton_4)
        self.horizontalLayout.addLayout(self.formLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_5 = QtWidgets.QLabel(SettingsForm)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_6 = QtWidgets.QLabel(SettingsForm)
        self.label_6.setObjectName("label_6")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_4 = QtWidgets.QLineEdit(SettingsForm)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.label_7 = QtWidgets.QLabel(SettingsForm)
        self.label_7.setObjectName("label_7")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_5 = QtWidgets.QLineEdit(SettingsForm)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
        self.label_8 = QtWidgets.QLabel(SettingsForm)
        self.label_8.setObjectName("label_8")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_6 = QtWidgets.QLineEdit(SettingsForm)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_6)
        self.pushButton_5 = QtWidgets.QPushButton(SettingsForm)
        self.pushButton_5.setObjectName("pushButton_5")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pushButton_5)
        self.verticalLayout.addLayout(self.formLayout_5)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(SettingsForm)
        QtCore.QMetaObject.connectSlotsByName(SettingsForm)

    def retranslateUi(self, SettingsForm):
        _translate = QtCore.QCoreApplication.translate
        SettingsForm.setWindowTitle(_translate("SettingsForm", "Настройки"))
        self.label.setText(_translate("SettingsForm", "Настройки редмайна"))
        self.pushButton_2.setText(_translate("SettingsForm", "+"))
        self.pushButton_3.setText(_translate("SettingsForm", "[...]"))
        self.pushButton.setText(_translate("SettingsForm", "-"))
        self.label_2.setText(_translate("SettingsForm", "Адрес"))
        self.label_3.setText(_translate("SettingsForm", "Логин"))
        self.label_4.setText(_translate("SettingsForm", "Пароль"))
        self.pushButton_4.setText(_translate("SettingsForm", "Сохранить"))
        self.label_5.setText(_translate("SettingsForm", "Настройки evolution"))
        self.label_6.setText(_translate("SettingsForm", "Адрес"))
        self.label_7.setText(_translate("SettingsForm", "Логин"))
        self.label_8.setText(_translate("SettingsForm", "Пароль"))
        self.pushButton_5.setText(_translate("SettingsForm", "Сохранить"))

